### ISSUE TITLE
Add Sentinel Support

### ISSUE THREAD

**Issue by severindellsperger** [josiahcarlson/rom#152]
Is it planned to implement Redis Sentinel support?

I have now solved it via following implementation:
```
def get_redis_sentinel_connections():
    return Sentinel(
        [
            ("sentinel.test.svc.cluster.local", 5000),
        ],
        socket_timeout=0.1,
    )


def connect_rom():
    redis_master_connection_tuple = get_redis_sentinel_connections().discover_master(
        "mymaster"
    )
    rom.util.set_connection_settings(
        host=redis_master_connection_tuple[0],
        port=redis_master_connection_tuple[1],
        db=3,
        password="test-password",
    )
```

It workes to connect to the cluster.
However, after the master node fails, the connection fails, and a manual reconnection must be executed.
Has anyone a better solution, or is it even planned to implement it in the future?
How do you propose a check if the connection is clear and a reconnection if it's not?

Would be handy if someone could give me tips on this topic.

**Comment by Frank5000** [comment]
Also curious, is this even possible in normal `redis-py` without re-initializing `redis.Redis` each time?

One idea is you could implement a `Redis` subclass with automatic retry and do `get_redis_sentinel_connections().master_for('mymaster', redis_class=RetryRedis)`

**Comment by severindellsperger** [comment]
Indeed, good question...
I have to take a look at it, maybe it is possible if I directly use `master_for` and not `discover_master`.

How did you think could a possible implementation look like in the `RetryRedis` class?

**Comment by severindellsperger** [comment]
So, the reconnection seems to work if the connection is made via Sentinel.
```
rom.util.CONNECTION = Sentinel(
  [
      ("sentinel.test.svc.cluster.local", 5000),
  ],
  socket_timeout=0.1,
  db=3,
  password="test-password",
).master_for("mymaster", socket_timeout=0.1)

```

If I write data, a `ConnectionError` is raised. However, after a few retries, the new master is found automatically and the data can be processed.
I think we will catch this exception, wait for a little time and try again. 
I think it should work.

What do the others think about this solution with sentinel support? Any inputs/thoughts?
Would be glad if there is a more beautiful solution.

============================================================================

Here an example log from my tests:

```
>>> router3.save()
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 1198, in get_connection
    if connection.can_read():
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/rom/model.py", line 498, in save
    ret, data = self._apply_changes(
  File "/usr/local/lib/python3.9/site-packages/rom/model.py", line 468, in _apply_changes
    redis_writer_lua(conn, cls._pkey, model, id_only, unique, udeleted,
  File "/usr/local/lib/python3.9/site-packages/rom/model.py", line 1140, in redis_writer_lua
    result = _redis_writer_lua(conn, [], [namespace, id] + data)
  File "/usr/local/lib/python3.9/site-packages/rom/util.py", line 906, in call
    return conn.execute_command(
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 1202, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.9/site-packages/redis/sentinel.py", line 44, in connect
    self.connect_to(self.connection_pool.get_master_address())
  File "/usr/local/lib/python3.9/site-packages/redis/sentinel.py", line 34, in connect_to
    super(SentinelManagedConnection, self).connect()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 561, in connect
    raise TimeoutError("Timeout connecting to server")
redis.exceptions.TimeoutError: Timeout connecting to server
>>> router3.save()
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/rom/model.py", line 498, in save
    ret, data = self._apply_changes(
  File "/usr/local/lib/python3.9/site-packages/rom/model.py", line 468, in _apply_changes
    redis_writer_lua(conn, cls._pkey, model, id_only, unique, udeleted,
  File "/usr/local/lib/python3.9/site-packages/rom/model.py", line 1140, in redis_writer_lua
    result = _redis_writer_lua(conn, [], [namespace, id] + data)
  File "/usr/local/lib/python3.9/site-packages/rom/util.py", line 913, in call
    return conn.execute_command(
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.9/site-packages/redis/sentinel.py", line 44, in connect
    self.connect_to(self.connection_pool.get_master_address())
  File "/usr/local/lib/python3.9/site-packages/redis/sentinel.py", line 34, in connect_to
    super(SentinelManagedConnection, self).connect()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 561, in connect
    raise TimeoutError("Timeout connecting to server")
redis.exceptions.TimeoutError: Timeout connecting to server
>>> router3.save()
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/rom/model.py", line 498, in save
    ret, data = self._apply_changes(
  File "/usr/local/lib/python3.9/site-packages/rom/model.py", line 468, in _apply_changes
    redis_writer_lua(conn, cls._pkey, model, id_only, unique, udeleted,
  File "/usr/local/lib/python3.9/site-packages/rom/model.py", line 1140, in redis_writer_lua
    result = _redis_writer_lua(conn, [], [namespace, id] + data)
  File "/usr/local/lib/python3.9/site-packages/rom/util.py", line 913, in call
    return conn.execute_command(
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.9/site-packages/redis/sentinel.py", line 44, in connect
    self.connect_to(self.connection_pool.get_master_address())
  File "/usr/local/lib/python3.9/site-packages/redis/sentinel.py", line 34, in connect_to
    super(SentinelManagedConnection, self).connect()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 561, in connect
    raise TimeoutError("Timeout connecting to server")
redis.exceptions.TimeoutError: Timeout connecting to server
>>> router3.save()
5
```
