### ISSUE TITLE
get_by(**) bug for '%' name

### ISSUE THREAD

**Issue by amaozhao** [josiahcarlson/rom#96]
I created a model with it's name is '%', but cannot found it use get_by or filter.
'get_by' method with some error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "rom/model.py", line 605, in get_by
    return cls.get(ids[0] if single else ids)
  File "rom/model.py", line 536, in get
    out[i] = cls(_loading=True, **data)
  File "rom/model.py", line 234, in __init__
    setattr(self, attr, data)
  File "rom/columns.py", line 317, in __set__
    self._init_(obj, *value)
  File "rom/columns.py", line 300, in _init_
    raise MissingColumn("%s.%s cannot be missing"%(self._model, self._attr))

**Comment by timeartist** [comment]
% is a reserved character in python strings.  You need to escape it.

**Comment by josiahcarlson** [comment]
Rom only supports attributes with valid names in Python. `%` is not considered a valid name in Python.
